output "main_vpc_id" {
    description = "The ID of the main VPC"
    value = aws_vpc.vpc.id
}

output "private_subnet_id" {
    description = "The private subnet ID generated by the module"
    value = aws_subnet.private.id
}

output "public_subnet_id" {
    description = "The public subnet ID generated by the module"
    value = aws_subnet.public.id
}